/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_test_DecodeWlt */

#ifndef _Included_DecodeWlt
#define _Included_DecodeWlt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_test_DecodeWlt
 * Method:    Wlt2Bmp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ntga_card_DecodeWlt_Wlt2Bmp
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
